name: Test
on:
  push:
    branches:
      - user-creation-feature

jobs:
  run-action:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 23.x
        uses: actions/setup-node@v2
        with:
          node-version: 23.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test the code
        run: npm test
